# ATM System Configuration
# Environment-based configuration for development, testing, and production

development:
  server:
    host: "127.0.0.1"
    port: 8000
    base_url: "http://localhost:8000"
  
production:
  server:
    host: "16.170.240.218"
    port: 8000
    base_url: "http://16.170.240.218:8000"
    
testing:
  server:
    host: "127.0.0.1"
    port: 8000
    base_url: "http://localhost:8000"

# Default environment if none specified
default_environment: "production"