# ATM System Configuration
# Environment-based configuration for development, testing, and production

development:
  server:
    host: "127.0.0.1"
    port: 8000
    base_url: "http://localhost:8000"
  
production:
  server:
    host: "0.0.0.0"
    port: 8000
    base_url: "https://your-server-domain.com"
    
testing:
  server:
    host: "127.0.0.1"
    port: 8000
    base_url: "http://localhost:8000"

# Default environment if none specified
default_environment: "development"