# ATM System Configuration
# Environment-based configuration for development, testing, and production

development:
  server:
    host: "127.0.0.1"
    port: 80
    base_url: "http://localhost"
  
production:
  server:
    host: "0.0.0.0"
    port: 80
    base_url: "http://16.170.240.218"
    
testing:
  server:
    host: "127.0.0.1"
    port: 80
    base_url: "http://localhost"

# Default environment if none specified
default_environment: "production"